#!/bin/sh
# Created by: KalleDK <plexmaintainer@k-moeller.dk>
#
# $FreeBSD$
#
# PROVIDE: plexmediaserver_plexpass
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable the Plex Media Server:
#
# plexmediaserver_plexpass_enable="YES"
#
# plexmediaserver_plexpass_support_path="/usr/local/plexdata" # Plex data: logs, media metadata, settings, etc
#
# plexmediaserver_plexpass_tmp="/var/tmp/plex" # configure tmp directory used for the transcoding process if desired
#
# plexmediaserver_plexpass_maxplugins="6" # Maximum number of background plugin procs. May have to raise in rare cases.
#

. /etc/rc.subr

name=plexmediaserver_plexpass
rcvar=plexmediaserver_plexpass_enable
load_rc_config $name

: ${plexmediaserver_plexpass_enable:=NO}
: ${plexmediaserver_plexpass_support_path="/usr/local/plexdata-plexpass"}
: ${plexmediaserver_plexpass_user="plex"}
: ${plexmediaserver_plexpass_group="plex"}
: ${plexmediaserver_plexpass_maxplugins=6}

command=/usr/sbin/daemon
procname="/usr/local/share/plexmediaserver-plexpass/Plex_Media_Server"
pidfile=/var/run/plex/plex-daemon.pid
plexpidfile=/var/run/plex/plex-server.pid
command_args="-r -P $pidfile -f ${procname}"
start_precmd=plex_precmd
stop_precmd=plex_stop_precmd
stop_cmd=plex_stop

plex_precmd()
{
	#Set identification variables for FreeNAS; with fallback to FreeBSD
	if [ -f "/etc/version" ]; then
	  export PLEX_MEDIA_SERVER_INFO_VENDOR="$(cat /etc/version|cut -d- -f1)"
	  export PLEX_MEDIA_SERVER_INFO_DEVICE=NAS
	  export PLEX_MEDIA_SERVER_INFO_MODEL="$(uname -m)"
	  export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$(cat /etc/version|cut -d- -f2-)"
	else
	  export PLEX_MEDIA_SERVER_INFO_VENDOR=FreeBSD
	  export PLEX_MEDIA_SERVER_INFO_DEVICE=PC
	  export PLEX_MEDIA_SERVER_INFO_MODEL="$(uname -m)"
	  export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$(uname -r)"
	fi
	export SUPPORT_PATH="${plexmediaserver_plexpass_support_path}"
	export HOME="${plexmediaserver_plexpass_support_path}/Plex Media Server"
	export PYTHONHOME="/usr/local/share/plexmediaserver-plexpass/Resources/Python"
	export SCRIPTPATH="/usr/local/share/plexmediaserver-plexpass"
	export LD_LIBRARY_PATH="${SCRIPTPATH}/lib"
	export PLEX_MEDIA_SERVER_HOME="${SCRIPTPATH}"
	export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=${plexmediaserver_plexpass_maxplugins}
	export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=${plexmediaserver_plexpass_support_path}
	export PLEX_MEDIA_SERVER_PIDFILE=${plexpidfile}
	export PLEX_MEDIA_SERVER_LOG_DIR="${plexmediaserver_plexpass_support_path}/Plex Media Server/Logs"
	export PATH="${SCRIPTPATH}/Resources/Python/bin:${PATH}"
	export LC_ALL="en_US.UTF-8"
	export LANG="en_US.UTF-8"
	ulimit -s 3000

	if [ ! -d ${plexpidfile%/*} ]; then
		install -d -o ${plexmediaserver_plexpass_user} ${plexpidfile%/*};
	fi
	
	if [ ! -d "${plexmediaserver_plexpass_support_path}/Plex Media Server" ]; then
		install -d -g ${plexmediaserver_plexpass_group} -o ${plexmediaserver_plexpass_user} "${plexmediaserver_plexpass_support_path}/Plex Media Server";
	fi

	if [ ! -d "${plexmediaserver_plexpass_support_path}/Plex" ]; then
		install -d -g ${plexmediaserver_plexpass_group} -o ${plexmediaserver_plexpass_user} "${plexmediaserver_plexpass_support_path}/Plex";
	fi
	
	if [ ${plexmediaserver_plexpass_tmp} ]; then 
		export TMPDIR=${plexmediaserver_plexpass_tmp};
		install -d -g ${plexmediaserver_plexpass_group} -o ${plexmediaserver_plexpass_user} "${plexmediaserver_plexpass_tmp}";
	fi
}

plex_stop_precmd()
{
	killall -9 -u ${plexmediaserver_plexpass_user}
}

plex_stop()
{
	pkill -9 -F ${pidfile} >/dev/null 2>/dev/null
	return 0
}

run_rc_command "$1"
